package com.server;

import org.apache.logging.log4j.*;

import java.io.File;
import java.io.FileWriter;
/**
 * Class containing fields and methods for logging events generated by the application to a file.
 */
public class Logs {
    /**
     * Attribute used to set the appropriate type of event log.
     */
    private final Logger log;
    /**
     * Attribute specifying the event message.
     */
    private static String message;
    /**
     * Attribute specifying the name of the class from which events are currently being retrieved.
     */
    private static String className;

    /**
     * Constructor allowing the initialization of final fields and calling the method responsible for writing the event to a file.
     *
     * @param className   parameter specifying the name of the class from which events are currently being retrieved
     * @param messageType parameter specifying the type of event
     * @param message     parameter specifying the event message
     */
    public Logs(String className, String messageType, String message) {
        Logs.message = message;
        Logs.className = className;
        this.log = LogManager.getLogger(className + ".class");
        writeToFile(messageType);
    }

    /**
     * Method responsible for writing the event to a file.
     *
     * @param messageType parameter specifying the type of event
     */
    protected void writeToFile(String messageType) {
        try {
            File folder = new File("logs");
            if (!folder.exists())
                folder.mkdir();
            File file = new File("logs/logs.log");
            FileWriter fileWriter = new FileWriter(file, true);
            switch (messageType) {
                case "fatal" -> log.fatal(Logs.message);
                case "info" -> log.info(Logs.message);
                case "error" -> log.error(Logs.message);
            }
            fileWriter.write("[" + messageType.toUpperCase() + "] " + Logs.className + ": " + Logs.message + "\n");
            fileWriter.close();

        } catch (Exception e) {
            new LogsServer(className, messageType, message).setMessage(e.getMessage());
            log.fatal("[ " + new java.util.Date() + " ] " + "Error writing log to file");
        }
    }
}