/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package oferty;
//package oferty;

import java.awt.Color;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.util.regex.Pattern;
import javax.swing.*;
import javax.swing.border.LineBorder;

/**
 *
 * @author Kamil
 */
public class Payment extends javax.swing.JFrame {
    //1234 4567 8901 2345
    private boolean methodChoosed = false;
    private static final String firstNameAndLastNamePattern = "^[\\p{L}\\s'-]+$";
    private static final Pattern compiledfirstNameAndLastNamePattern = Pattern.compile(firstNameAndLastNamePattern);
    private static final String creditCardNumberPattern = "^\\d{4}[ -]?\\d{4}[ -]?\\d{4}[ -]?\\d{4}$";
    private static final Pattern compiledcreditCardNumberPattern = Pattern.compile(creditCardNumberPattern);
    private static final String cvvPattern = "^\\d{3,4}$";
    private static final Pattern compiledcvvPattern = Pattern.compile(cvvPattern);
    private static final String monthPattern = "^(0?[1-9]|1[0-2])$";
    private static final Pattern compiledmonthPattern = Pattern.compile(monthPattern);
    private static final String yearPattern = "^((20)\\d{2}|\\d{2})$";
    private static final Pattern compiledyearPattern = Pattern.compile(yearPattern);
    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
        setTitle("Płatność kartą kredytową");
        mastercard.setFocusable(false);
        visa.setFocusable(false);
        discover.setFocusable(false);
        miejsce_na_blad.setForeground(Color.RED);
        miejsce_na_blad.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        miejsce_na_blad = new javax.swing.JLabel();
        metoda_platnosci = new javax.swing.JLabel();
        panel_z_wyborem = new javax.swing.JPanel();
        mastercard = new javax.swing.JButton();
        visa = new javax.swing.JButton();
        discover = new javax.swing.JButton();
        wlasciciel = new javax.swing.JLabel();
        panel_imie_nazwisko = new javax.swing.JPanel();
        imie_nazwisko = new javax.swing.JLabel();
        imie_nazwisko_dane = new javax.swing.JTextField();
        numer = new javax.swing.JLabel();
        panel_numer = new javax.swing.JPanel();
        numer_karty = new javax.swing.JLabel();
        numer_karty_dane = new javax.swing.JTextField();
        cvv = new javax.swing.JLabel();
        cvv_dane = new javax.swing.JTextField();
        termin_waznosci = new javax.swing.JLabel();
        panel_termin_waznosci = new javax.swing.JPanel();
        miesiac = new javax.swing.JLabel();
        miesiac_Dane = new javax.swing.JTextField();
        rok = new javax.swing.JLabel();
        rok_dane = new javax.swing.JTextField();
        zaplac = new javax.swing.JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(450, 124));
        setPreferredSize(new java.awt.Dimension(548, 640));

        miejsce_na_blad.setBackground(new java.awt.Color(255, 255, 255));
        miejsce_na_blad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        miejsce_na_blad.setText("Miejsce na informacje o błędzie");
        miejsce_na_blad.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        metoda_platnosci.setBackground(new java.awt.Color(210, 180, 140));
        metoda_platnosci.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        metoda_platnosci.setText("Metoda płatności");
        metoda_platnosci.setOpaque(true);

        panel_z_wyborem.setBackground(new java.awt.Color(151, 123, 92));

        mastercard.setIcon(new javax.swing.ImageIcon("src/img/mastercard.png")); // NOI18N
        //nowe
        mastercard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mastercardActionPerformed(evt);
            }
        });
        //nowe
        mastercard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        visa.setIcon(new javax.swing.ImageIcon("src/img/visa.png")); // NOI18N
        //nowe
        visa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visaActionPerformed(evt);
            }
        });
        //nowe
        visa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        discover.setIcon(new javax.swing.ImageIcon("src/img/discover-logo.png")); // NOI18N
        //nowe
        discover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discoverActionPerformed(evt);
            }
        });
        //nowe
        discover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panel_z_wyboremLayout = new javax.swing.GroupLayout(panel_z_wyborem);
        panel_z_wyborem.setLayout(panel_z_wyboremLayout);
        panel_z_wyboremLayout.setHorizontalGroup(
            panel_z_wyboremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_z_wyboremLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mastercard, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(visa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(discover, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        panel_z_wyboremLayout.setVerticalGroup(
            panel_z_wyboremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_z_wyboremLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_z_wyboremLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(mastercard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(visa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discover, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        wlasciciel.setBackground(new java.awt.Color(210, 180, 140));
        wlasciciel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        wlasciciel.setText("Właściciel");
        wlasciciel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        wlasciciel.setOpaque(true);

        panel_imie_nazwisko.setBackground(new java.awt.Color(151, 123, 92));

        imie_nazwisko.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        imie_nazwisko.setText("Imie i nazwisko:");

        imie_nazwisko_dane.setBackground(new java.awt.Color(242, 242, 242));
        imie_nazwisko_dane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imie_nazwisko_daneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_imie_nazwiskoLayout = new javax.swing.GroupLayout(panel_imie_nazwisko);
        panel_imie_nazwisko.setLayout(panel_imie_nazwiskoLayout);
        panel_imie_nazwiskoLayout.setHorizontalGroup(
            panel_imie_nazwiskoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_imie_nazwiskoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_imie_nazwiskoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_imie_nazwiskoLayout.createSequentialGroup()
                        .addComponent(imie_nazwisko)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(imie_nazwisko_dane))
                .addContainerGap())
        );
        panel_imie_nazwiskoLayout.setVerticalGroup(
            panel_imie_nazwiskoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_imie_nazwiskoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imie_nazwisko)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imie_nazwisko_dane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        numer.setBackground(new java.awt.Color(210, 180, 140));
        numer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numer.setText("Numer");
        numer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        numer.setOpaque(true);

        panel_numer.setBackground(new java.awt.Color(151, 123, 92));

        numer_karty.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        numer_karty.setText("Numer karty kredytowej:");

        numer_karty_dane.setBackground(new java.awt.Color(242, 242, 242));
        numer_karty_dane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numer_karty_daneActionPerformed(evt);
            }
        });

        cvv.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        cvv.setText("CVV:");

        cvv_dane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvv_daneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_numerLayout = new javax.swing.GroupLayout(panel_numer);
        panel_numer.setLayout(panel_numerLayout);
        panel_numerLayout.setHorizontalGroup(
            panel_numerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_numerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_numerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numer_karty_dane, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numer_karty))
                .addGap(18, 18, 18)
                .addGroup(panel_numerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cvv)
                    .addComponent(cvv_dane, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        panel_numerLayout.setVerticalGroup(
            panel_numerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_numerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_numerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numer_karty)
                    .addComponent(cvv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_numerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numer_karty_dane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cvv_dane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        termin_waznosci.setBackground(new java.awt.Color(210, 180, 140));
        termin_waznosci.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        termin_waznosci.setText("Termin ważności");
        termin_waznosci.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        termin_waznosci.setOpaque(true);

        panel_termin_waznosci.setBackground(new java.awt.Color(151, 123, 92));

        miesiac.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        miesiac.setText("Miesiąc:");

        miesiac_Dane.setBackground(new java.awt.Color(242, 242, 242));
        miesiac_Dane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miesiac_DaneActionPerformed(evt);
            }
        });

        rok.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        rok.setText("Rok:");

        rok_dane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rok_daneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_termin_waznosciLayout = new javax.swing.GroupLayout(panel_termin_waznosci);
        panel_termin_waznosci.setLayout(panel_termin_waznosciLayout);
        panel_termin_waznosciLayout.setHorizontalGroup(
            panel_termin_waznosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_termin_waznosciLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_termin_waznosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(miesiac_Dane, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(miesiac))
                .addGap(47, 47, 47)
                .addGroup(panel_termin_waznosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rok)
                    .addComponent(rok_dane, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        panel_termin_waznosciLayout.setVerticalGroup(
            panel_termin_waznosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_termin_waznosciLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_termin_waznosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(miesiac)
                    .addComponent(rok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_termin_waznosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(miesiac_Dane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rok_dane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        zaplac.setIcon(new javax.swing.ImageIcon("src/img/pay.png")); // NOI18N
        //nowe
        zaplac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zaplacActionPerformed(evt);
            }
        });
        //nowe
        zaplac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(miejsce_na_blad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panel_termin_waznosci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(termin_waznosci, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel_numer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numer, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wlasciciel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(metoda_platnosci, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel_z_wyborem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_imie_nazwisko, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(zaplac)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(miejsce_na_blad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(metoda_platnosci, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_z_wyborem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(wlasciciel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_imie_nazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(numer, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_numer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(termin_waznosci, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_termin_waznosci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(zaplac)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        miejsce_na_blad.getAccessibleContext().setAccessibleName("Miejs");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void zaplacActionPerformed(ActionEvent evt) {
        if(!methodChoosed)
            miejsce_na_blad.setText("Nie wybrano metody płatności.");
        else if(!compiledfirstNameAndLastNamePattern.matcher(imie_nazwisko_dane.getText()).matches()) {
            miejsce_na_blad.setText("Nieprawidłowe imię i nazwisko.");
        }
        else if(!compiledcreditCardNumberPattern.matcher(numer_karty_dane.getText()).matches()) {
            miejsce_na_blad.setText("Nieprawidłowy numer karty kredytowej.");
        }
        else if(!compiledcvvPattern.matcher(cvv_dane.getText()).matches()) {
            miejsce_na_blad.setText("Nieprawidłowy numer cvv.");
        }
        else if(!compiledmonthPattern.matcher(miesiac_Dane.getText()).matches()) {
            miejsce_na_blad.setText("Nieprawidłowy miesiąc ważności karty kredytowej.");
        }
        else if(!compiledyearPattern.matcher(rok_dane.getText()).matches()) {
            miejsce_na_blad.setText("Nieprawidłowy rok ważności karty kredytowej.");
        }
        else {
            Client.operate("addReservation");
            dispose();
        }
    }

    //nowe
    private void discoverActionPerformed(ActionEvent evt) {
        methodChoosed = true;
        miejsce_na_blad.setText("");
        /*discover.setFocusable(true);
        discover.requestFocusInWindow();*/
        discover.setBorder(new LineBorder(Color.BLUE, 3));
        visa.setBorder(null);
        mastercard.setBorder(null);
    }

    //nowe
    private void visaActionPerformed(ActionEvent evt) {
        methodChoosed = true;
        miejsce_na_blad.setText("");
        /*visa.setFocusable(true);
        visa.requestFocusInWindow();*/
        visa.setBorder(new LineBorder(Color.BLUE, 3));
        mastercard.setBorder(null);
        discover.setBorder(null);
    }

    //NOWE
    private void mastercardActionPerformed(ActionEvent evt) {
        methodChoosed = true;
        miejsce_na_blad.setText("");
        /*mastercard.setFocusable(true);
        mastercard.requestFocusInWindow();*/
        mastercard.setBorder(new LineBorder(Color.BLUE, 3));
        visa.setBorder(null);
        discover.setBorder(null);
    }

    private void imie_nazwisko_daneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imie_nazwisko_daneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imie_nazwisko_daneActionPerformed

    private void numer_karty_daneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numer_karty_daneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numer_karty_daneActionPerformed

    private void cvv_daneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvv_daneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvv_daneActionPerformed

    private void miesiac_DaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miesiac_DaneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miesiac_DaneActionPerformed

    private void rok_daneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rok_daneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rok_daneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    private void setTitle(Color black) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cvv;
    private javax.swing.JTextField cvv_dane;
    private javax.swing.JButton discover;
    private javax.swing.JLabel imie_nazwisko;
    private javax.swing.JTextField imie_nazwisko_dane;
    private javax.swing.JButton mastercard;
    private javax.swing.JLabel metoda_platnosci;
    private javax.swing.JLabel miejsce_na_blad;
    private javax.swing.JLabel miesiac;
    private javax.swing.JTextField miesiac_Dane;
    private javax.swing.JLabel numer;
    private javax.swing.JLabel numer_karty;
    private javax.swing.JTextField numer_karty_dane;
    private javax.swing.JPanel panel_imie_nazwisko;
    private javax.swing.JPanel panel_numer;
    private javax.swing.JPanel panel_termin_waznosci;
    private javax.swing.JPanel panel_z_wyborem;
    private javax.swing.JLabel rok;
    private javax.swing.JTextField rok_dane;
    private javax.swing.JLabel termin_waznosci;
    private javax.swing.JButton visa;
    private javax.swing.JLabel wlasciciel;
    private javax.swing.JButton zaplac;
    // End of variables declaration//GEN-END:variables
}
