package com.server.logs;

import java.util.ArrayList;
import java.util.List;

/**
 * A class containing fields and methods operating on events generated by administrators' actions.
 */
public class LogsAdmins extends Logs {

    /**
     * An attribute representing a list that stores events generated by administrators' actions.
     */
    public static List<String> logs = new ArrayList<>();

    /**
     * A constructor calling the base class constructor and the method responsible for saving the event to the list.
     *
     * @param className   parameter specifying the name of the class from which events are currently being retrieved
     * @param messageType parameter specifying the type of event
     * @param message     parameter specifying the event message
     */
    public LogsAdmins(String className, String messageType, String message) {
        super(className, messageType, message);
        setMessage(message);
    }

    /**
     * Saves the event to the list.
     *
     * @param message parameter specifying the event message
     */
    public void setMessage(String message) {
        logs.add(message);
    }
}