
import java.awt.*;
import java.io.*;
import java.net.Socket;
import java.net.UnknownHostException;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author zuzan
 */
public class Dashboard extends javax.swing.JFrame {
    public static String adminName = "";
    public static int howManyClients;
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        getContentPane().setBackground(new Color(215,198,151));
        //nowe
        generateData();
        /*testy
        tripsNumberLabel.setText("50");
        reservationsNumberLabel.setText("50");
        clientsNumberLabel.setText("50");
        incomeNumberLabel.setText("5000 zł");
        
        image1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.jpg")));
        name1Label.setText("Real Kathamundu to Delphi");
        sold1Label.setText("17");
        price1Label.setText("5000 zł");
        type1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/planeICON.png")));
        
        image2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.jpg")));
        name2Label.setText("Real Kathamundu to Delphi");
        sold2Label.setText("17");
        price2Label.setText("5000 zł");
        type2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/planeICON.png")));
        
        image3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.jpg")));
        name3Label.setText("Real Kathamundu to Delphi");
        sold3Label.setText("17");
        price3Label.setText("5000 zł");
        type3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/planeICON.png")));
        
        image4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.jpg")));
        name4Label.setText("Real Kathamundu to Delphi");
        sold4Label.setText("17");
        price4Label.setText("5000 zł");
        type4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/planeICON.png")));
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        adminPanel = new javax.swing.JPanel();
        adminIconLabel = new javax.swing.JLabel();
        adminNameLabel = new javax.swing.JLabel();
        adminLabel = new javax.swing.JLabel();
        optionsPanel = new javax.swing.JPanel();
        panelButton = new javax.swing.JButton();
        clientsButton = new javax.swing.JButton();
        tripsButton = new javax.swing.JButton();
        reservationsButton = new javax.swing.JButton();
        databaseButton = new javax.swing.JButton();
        topPanel = new javax.swing.JPanel();
        logOutButton = new javax.swing.JButton();
        tripsNumberPanel = new javax.swing.JPanel();
        tripsCaption = new javax.swing.JLabel();
        tripsNumberLabel = new javax.swing.JLabel();
        reservationsNumberPanel = new javax.swing.JPanel();
        reservationsCaption = new javax.swing.JLabel();
        reservationsNumberLabel = new javax.swing.JLabel();
        profitNumberPanel = new javax.swing.JPanel();
        incomeNumberLabel = new javax.swing.JLabel();
        incomeCaption = new javax.swing.JLabel();
        clientsNumberPanel = new javax.swing.JPanel();
        clientsNumberLabel = new javax.swing.JLabel();
        clientsCaption = new javax.swing.JLabel();
        bestSellingPanel = new javax.swing.JPanel();
        bestSellingTitleLabel = new javax.swing.JLabel();
        bestSellingHeadingPanel = new javax.swing.JPanel();
        bestSellingHeadingNameLabel = new javax.swing.JLabel();
        bestSellingHeadingSoldLabel = new javax.swing.JLabel();
        bestSellingHeadingPriceLabel = new javax.swing.JLabel();
        bestSellingHeadingTypeLabel = new javax.swing.JLabel();
        tripPanel1 = new javax.swing.JPanel();
        image1Label = new javax.swing.JLabel();
        name1Label = new javax.swing.JLabel();
        sold1Label = new javax.swing.JLabel();
        price1Label = new javax.swing.JLabel();
        type1Label = new javax.swing.JLabel();
        tripPanel2 = new javax.swing.JPanel();
        image2Label = new javax.swing.JLabel();
        name2Label = new javax.swing.JLabel();
        sold2Label = new javax.swing.JLabel();
        price2Label = new javax.swing.JLabel();
        type2Label = new javax.swing.JLabel();
        tripPanel3 = new javax.swing.JPanel();
        type3Label = new javax.swing.JLabel();
        price3Label = new javax.swing.JLabel();
        sold3Label = new javax.swing.JLabel();
        image3Label = new javax.swing.JLabel();
        name3Label = new javax.swing.JLabel();
        tripPanel4 = new javax.swing.JPanel();
        type4Label = new javax.swing.JLabel();
        price4Label = new javax.swing.JLabel();
        sold4Label = new javax.swing.JLabel();
        image4Label = new javax.swing.JLabel();
        name4Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel Admina");

        menuPanel.setBackground(new java.awt.Color(118, 98, 75));

        adminPanel.setBackground(new java.awt.Color(118, 98, 75));

        adminIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/adminLOGO.png"))); // NOI18N
        adminIconLabel.setText("jLabel1");
        adminIconLabel.setMaximumSize(new java.awt.Dimension(70, 70));
        adminIconLabel.setMinimumSize(new java.awt.Dimension(70, 70));
        adminIconLabel.setPreferredSize(new java.awt.Dimension(70, 70));

        adminNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        adminNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        adminNameLabel.setPreferredSize(new java.awt.Dimension(73, 25));

        adminLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adminLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminLabel.setText("Admin");

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(adminIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
            .addComponent(adminLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(adminIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(adminNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(adminLabel)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        optionsPanel.setBackground(new java.awt.Color(151, 123, 92));
        optionsPanel.setMinimumSize(new java.awt.Dimension(180, 200));
        optionsPanel.setPreferredSize(new java.awt.Dimension(180, 230));

        panelButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        panelButton.setText("   Panel");
        panelButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelButton.setContentAreaFilled(false);
        panelButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        //nowe
        Color hoverColor = new Color(190, 190, 192);
        panelButton.getModel().addChangeListener(e -> {
            ButtonModel model = (ButtonModel) e.getSource();
            if(model.isRollover()) {
                panelButton.setForeground(hoverColor);
                panelButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            }
            else
                panelButton.setForeground(null);
        });

        clientsButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        clientsButton.setText("Klienci");
        clientsButton.setContentAreaFilled(false);
        clientsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        clientsButton.setPreferredSize(new java.awt.Dimension(75, 46));
        //nowe
        clientsButton.getModel().addChangeListener(e -> {
            ButtonModel model = (ButtonModel) e.getSource();
            if(model.isRollover()) {
                clientsButton.setForeground(hoverColor);
                clientsButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            }
            else
                clientsButton.setForeground(null);
        });

        tripsButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tripsButton.setText("Wycieczki");
        tripsButton.setContentAreaFilled(false);
        tripsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tripsButton.setPreferredSize(new java.awt.Dimension(75, 46));
        //nowe
        tripsButton.getModel().addChangeListener(e -> {
            ButtonModel model = (ButtonModel) e.getSource();
            if(model.isRollover()) {
                tripsButton.setForeground(hoverColor);
                tripsButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            }
            else
                tripsButton.setForeground(null);
        });

        reservationsButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        reservationsButton.setText("Rezerwacje");
        reservationsButton.setContentAreaFilled(false);
        reservationsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reservationsButton.setPreferredSize(new java.awt.Dimension(75, 46));
        //nowe
        reservationsButton.getModel().addChangeListener(e -> {
            ButtonModel model = (ButtonModel) e.getSource();
            if(model.isRollover()) {
                reservationsButton.setForeground(hoverColor);
                reservationsButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            }
            else
                reservationsButton.setForeground(null);
        });

        databaseButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        databaseButton.setText("Baza danych");
        databaseButton.setContentAreaFilled(false);
        databaseButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        databaseButton.setPreferredSize(new java.awt.Dimension(75, 46));
        //nowe
        databaseButton.getModel().addChangeListener(e -> {
            ButtonModel model = (ButtonModel) e.getSource();
            if(model.isRollover()) {
                databaseButton.setForeground(hoverColor);
                databaseButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            }
            else
                databaseButton.setForeground(null);
        });

        javax.swing.GroupLayout optionsPanelLayout = new javax.swing.GroupLayout(optionsPanel);
        optionsPanel.setLayout(optionsPanelLayout);
        optionsPanelLayout.setHorizontalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(clientsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tripsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(reservationsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(databaseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        optionsPanelLayout.setVerticalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(clientsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tripsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(reservationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(databaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(optionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addComponent(adminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        topPanel.setBackground(new java.awt.Color(151, 123, 92));
        topPanel.setPreferredSize(new java.awt.Dimension(205, 34));

        logOutButton.setBackground(new java.awt.Color(242, 242, 242));
        logOutButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        logOutButton.setForeground(new java.awt.Color(255, 255, 255));
        logOutButton.setText("Wyloguj");
        logOutButton.setContentAreaFilled(false);
        logOutButton.setPreferredSize(new java.awt.Dimension(74, 34));
        //nowe
        logOutButton.getModel().addChangeListener(e -> {
            ButtonModel model = (ButtonModel) e.getSource();
            if(model.isRollover()) {
                logOutButton.setForeground(Color.lightGray);
                logOutButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            }
            else
                logOutButton.setForeground(Color.white);
        });

        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tripsNumberPanel.setBackground(new java.awt.Color(175, 157, 121));
        tripsNumberPanel.setPreferredSize(new java.awt.Dimension(215, 130));

        tripsCaption.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tripsCaption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tripsCaption.setText("Wycieczek");
        tripsCaption.setPreferredSize(new java.awt.Dimension(61, 22));

        tripsNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 42)); // NOI18N
        tripsNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tripsNumberLabel.setPreferredSize(new java.awt.Dimension(48, 57));

        javax.swing.GroupLayout tripsNumberPanelLayout = new javax.swing.GroupLayout(tripsNumberPanel);
        tripsNumberPanel.setLayout(tripsNumberPanelLayout);
        tripsNumberPanelLayout.setHorizontalGroup(
            tripsNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tripsCaption, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
            .addComponent(tripsNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tripsNumberPanelLayout.setVerticalGroup(
            tripsNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tripsNumberPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tripsNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tripsCaption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        reservationsNumberPanel.setBackground(new java.awt.Color(175, 157, 121));
        reservationsNumberPanel.setPreferredSize(new java.awt.Dimension(215, 108));

        reservationsCaption.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        reservationsCaption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reservationsCaption.setText("Rezerwacji");
        reservationsCaption.setMaximumSize(new java.awt.Dimension(61, 22));
        reservationsCaption.setMinimumSize(new java.awt.Dimension(61, 22));
        reservationsCaption.setPreferredSize(new java.awt.Dimension(61, 22));

        reservationsNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 42)); // NOI18N
        reservationsNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reservationsNumberLabel.setPreferredSize(new java.awt.Dimension(48, 57));

        javax.swing.GroupLayout reservationsNumberPanelLayout = new javax.swing.GroupLayout(reservationsNumberPanel);
        reservationsNumberPanel.setLayout(reservationsNumberPanelLayout);
        reservationsNumberPanelLayout.setHorizontalGroup(
            reservationsNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reservationsCaption, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
            .addComponent(reservationsNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        reservationsNumberPanelLayout.setVerticalGroup(
            reservationsNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservationsNumberPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reservationsNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reservationsCaption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        profitNumberPanel.setBackground(new java.awt.Color(175, 157, 121));
        profitNumberPanel.setPreferredSize(new java.awt.Dimension(280, 130));

        incomeNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 42)); // NOI18N
        incomeNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        incomeNumberLabel.setPreferredSize(new java.awt.Dimension(178, 57));

        incomeCaption.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        incomeCaption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        incomeCaption.setText("Wpływów");

        javax.swing.GroupLayout profitNumberPanelLayout = new javax.swing.GroupLayout(profitNumberPanel);
        profitNumberPanel.setLayout(profitNumberPanelLayout);
        profitNumberPanelLayout.setHorizontalGroup(
            profitNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(incomeNumberLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
            .addComponent(incomeCaption, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        profitNumberPanelLayout.setVerticalGroup(
            profitNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profitNumberPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(incomeNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(incomeCaption)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        clientsNumberPanel.setBackground(new java.awt.Color(175, 157, 121));
        clientsNumberPanel.setPreferredSize(new java.awt.Dimension(215, 130));

        clientsNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 42)); // NOI18N
        clientsNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clientsNumberLabel.setPreferredSize(new java.awt.Dimension(48, 57));

        clientsCaption.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        clientsCaption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clientsCaption.setText("Klientów");

        javax.swing.GroupLayout clientsNumberPanelLayout = new javax.swing.GroupLayout(clientsNumberPanel);
        clientsNumberPanel.setLayout(clientsNumberPanelLayout);
        clientsNumberPanelLayout.setHorizontalGroup(
            clientsNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clientsNumberLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(clientsCaption, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
        );
        clientsNumberPanelLayout.setVerticalGroup(
            clientsNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientsNumberPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(clientsNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientsCaption)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bestSellingPanel.setBackground(new java.awt.Color(215, 198, 151));
        bestSellingPanel.setPreferredSize(new java.awt.Dimension(620, 300));

        bestSellingTitleLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        bestSellingTitleLabel.setText("Najlepiej sprzedające się wycieczki");

        bestSellingHeadingPanel.setBackground(new java.awt.Color(241, 227, 185));

        bestSellingHeadingNameLabel.setText("NAZWA");

        bestSellingHeadingSoldLabel.setText("SPRZEDANYCH");

        bestSellingHeadingPriceLabel.setText("CENA");

        bestSellingHeadingTypeLabel.setText("TYP");

        javax.swing.GroupLayout bestSellingHeadingPanelLayout = new javax.swing.GroupLayout(bestSellingHeadingPanel);
        bestSellingHeadingPanel.setLayout(bestSellingHeadingPanelLayout);
        bestSellingHeadingPanelLayout.setHorizontalGroup(
            bestSellingHeadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bestSellingHeadingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bestSellingHeadingNameLabel)
                .addGap(250, 250, 250)
                .addComponent(bestSellingHeadingSoldLabel)
                .addGap(74, 74, 74)
                .addComponent(bestSellingHeadingPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bestSellingHeadingTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        bestSellingHeadingPanelLayout.setVerticalGroup(
            bestSellingHeadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bestSellingHeadingPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(bestSellingHeadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bestSellingHeadingNameLabel)
                    .addComponent(bestSellingHeadingSoldLabel)
                    .addComponent(bestSellingHeadingPriceLabel)
                    .addComponent(bestSellingHeadingTypeLabel)))
        );

        tripPanel1.setBackground(new java.awt.Color(241, 227, 185));
        tripPanel1.setMinimumSize(new java.awt.Dimension(620, 50));
        tripPanel1.setPreferredSize(new java.awt.Dimension(620, 50));

        name1Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name1Label.setPreferredSize(new java.awt.Dimension(156, 16));

        sold1Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sold1Label.setPreferredSize(new java.awt.Dimension(14, 16));

        price1Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        price1Label.setPreferredSize(new java.awt.Dimension(49, 16));

        type1Label.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout tripPanel1Layout = new javax.swing.GroupLayout(tripPanel1);
        tripPanel1.setLayout(tripPanel1Layout);
        tripPanel1Layout.setHorizontalGroup(
            tripPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tripPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(sold1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(price1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(type1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        tripPanel1Layout.setVerticalGroup(
            tripPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(image1Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(type1Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(tripPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(tripPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(name1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tripPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sold1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(price1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tripPanel2.setBackground(new java.awt.Color(241, 227, 185));
        tripPanel2.setPreferredSize(new java.awt.Dimension(552, 50));

        name2Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name2Label.setPreferredSize(new java.awt.Dimension(156, 16));

        sold2Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sold2Label.setPreferredSize(new java.awt.Dimension(14, 16));

        price2Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        price2Label.setPreferredSize(new java.awt.Dimension(49, 16));

        javax.swing.GroupLayout tripPanel2Layout = new javax.swing.GroupLayout(tripPanel2);
        tripPanel2.setLayout(tripPanel2Layout);
        tripPanel2Layout.setHorizontalGroup(
            tripPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tripPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(sold2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(price2Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(type2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        tripPanel2Layout.setVerticalGroup(
            tripPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(image2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(tripPanel2Layout.createSequentialGroup()
                .addGroup(tripPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tripPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(tripPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sold2Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price2Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name2Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tripPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(type2Label, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tripPanel3.setBackground(new java.awt.Color(241, 227, 185));
        tripPanel3.setPreferredSize(new java.awt.Dimension(552, 50));

        price3Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        price3Label.setPreferredSize(new java.awt.Dimension(49, 16));

        sold3Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sold3Label.setPreferredSize(new java.awt.Dimension(14, 16));

        name3Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name3Label.setPreferredSize(new java.awt.Dimension(156, 16));
        name3Label.setRequestFocusEnabled(false);

        javax.swing.GroupLayout tripPanel3Layout = new javax.swing.GroupLayout(tripPanel3);
        tripPanel3.setLayout(tripPanel3Layout);
        tripPanel3Layout.setHorizontalGroup(
            tripPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tripPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(sold3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(price3Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(type3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        tripPanel3Layout.setVerticalGroup(
            tripPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tripPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(type3Label, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(tripPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(tripPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price3Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sold3Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name3Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
            .addComponent(image3Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tripPanel4.setBackground(new java.awt.Color(241, 227, 185));
        tripPanel4.setPreferredSize(new java.awt.Dimension(552, 50));

        price4Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        price4Label.setPreferredSize(new java.awt.Dimension(49, 16));

        sold4Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sold4Label.setPreferredSize(new java.awt.Dimension(14, 16));

        name4Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name4Label.setPreferredSize(new java.awt.Dimension(156, 16));

        javax.swing.GroupLayout tripPanel4Layout = new javax.swing.GroupLayout(tripPanel4);
        tripPanel4.setLayout(tripPanel4Layout);
        tripPanel4Layout.setHorizontalGroup(
            tripPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tripPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(sold4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(price4Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(type4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        tripPanel4Layout.setVerticalGroup(
            tripPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tripPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(tripPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price4Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sold4Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name4Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
            .addComponent(image4Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(type4Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bestSellingPanelLayout = new javax.swing.GroupLayout(bestSellingPanel);
        bestSellingPanel.setLayout(bestSellingPanelLayout);
        bestSellingPanelLayout.setHorizontalGroup(
            bestSellingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bestSellingHeadingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tripPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tripPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
            .addComponent(tripPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
            .addGroup(bestSellingPanelLayout.createSequentialGroup()
                .addComponent(bestSellingTitleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(tripPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
        bestSellingPanelLayout.setVerticalGroup(
            bestSellingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bestSellingPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(bestSellingTitleLabel)
                .addGap(15, 15, 15)
                .addComponent(bestSellingHeadingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(tripPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(tripPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(tripPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(tripPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(clientsNumberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(tripsNumberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(reservationsNumberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(bestSellingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(282, 282, 282)
                                .addComponent(profitNumberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(108, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reservationsNumberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tripsNumberPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addComponent(clientsNumberPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)))
                .addGap(20, 20, 20)
                .addComponent(profitNumberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(bestSellingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    //nowe
    private void generateData(){
       /* try{
            Socket socket = new Socket("localhost", 1522);
            InputStream socket_input = socket.getInputStream();
            DataInputStream socket_input_data = new DataInputStream(socket_input);
            OutputStream socket_output = socket.getOutputStream();
            DataOutputStream socket_output_data = new DataOutputStream(socket_output);
            socket_output_data.writeUTF("dashboardUpdate");
            socket_output_data.flush();*/
            //adminName = socket_input_data.readUTF();
            Client.operate("dashboardUpdate");
            adminNameLabel.setText(adminName);
           // howManyClients = socket_input_data.readInt();
            String howManyClientsString = String.valueOf(howManyClients);
            clientsNumberLabel.setText(howManyClientsString);
           /* socket_output_data.close();
            socket_input_data.close();
            socket.close();
        }catch (UnknownHostException e) {
            throw new RuntimeException(e);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }*/
    }
    //nowe
    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
       // StartPageFrame.admin_logged = false;
        dispose();
        new StartPageFrame().setVisible(true);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminIconLabel;
    private javax.swing.JLabel adminLabel;
    private javax.swing.JLabel adminNameLabel;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JLabel bestSellingHeadingNameLabel;
    private javax.swing.JPanel bestSellingHeadingPanel;
    private javax.swing.JLabel bestSellingHeadingPriceLabel;
    private javax.swing.JLabel bestSellingHeadingSoldLabel;
    private javax.swing.JLabel bestSellingHeadingTypeLabel;
    private javax.swing.JPanel bestSellingPanel;
    private javax.swing.JLabel bestSellingTitleLabel;
    private javax.swing.JButton clientsButton;
    private javax.swing.JLabel clientsCaption;
    private javax.swing.JLabel clientsNumberLabel;
    private javax.swing.JPanel clientsNumberPanel;
    private javax.swing.JButton databaseButton;
    private javax.swing.JLabel image1Label;
    private javax.swing.JLabel image2Label;
    private javax.swing.JLabel image3Label;
    private javax.swing.JLabel image4Label;
    private javax.swing.JLabel incomeCaption;
    private javax.swing.JLabel incomeNumberLabel;
    private javax.swing.JButton logOutButton;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel name1Label;
    private javax.swing.JLabel name2Label;
    private javax.swing.JLabel name3Label;
    private javax.swing.JLabel name4Label;
    private javax.swing.JPanel optionsPanel;
    private javax.swing.JButton panelButton;
    private javax.swing.JLabel price1Label;
    private javax.swing.JLabel price2Label;
    private javax.swing.JLabel price3Label;
    private javax.swing.JLabel price4Label;
    private javax.swing.JPanel profitNumberPanel;
    private javax.swing.JButton reservationsButton;
    private javax.swing.JLabel reservationsCaption;
    private javax.swing.JLabel reservationsNumberLabel;
    private javax.swing.JPanel reservationsNumberPanel;
    private javax.swing.JLabel sold1Label;
    private javax.swing.JLabel sold2Label;
    private javax.swing.JLabel sold3Label;
    private javax.swing.JLabel sold4Label;
    private javax.swing.JPanel topPanel;
    private javax.swing.JPanel tripPanel1;
    private javax.swing.JPanel tripPanel2;
    private javax.swing.JPanel tripPanel3;
    private javax.swing.JPanel tripPanel4;
    private javax.swing.JButton tripsButton;
    private javax.swing.JLabel tripsCaption;
    private javax.swing.JLabel tripsNumberLabel;
    private javax.swing.JPanel tripsNumberPanel;
    private javax.swing.JLabel type1Label;
    private javax.swing.JLabel type2Label;
    private javax.swing.JLabel type3Label;
    private javax.swing.JLabel type4Label;
    // End of variables declaration//GEN-END:variables
}
